config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper_openid_connect

  constraints subdomain: ['wordlid', 'wordlid.dev', 'signup', 'signup.dev', 'join', 'join.dev'] do
    scope module: 'public' do
      get  '/', to: 'home#index', as: 'public'
      post '/', to: 'home#create'
    end
  end

  constraints subdomain: ['koala', 'koala.dev', 'leden', 'leden.dev', 'members', 'members.dev'] do
    authenticate :user, ->(u) { !u.admin? } do
      scope module: 'members' do
        root to: 'home#index', as: :users_root

        get '/activities/69420', to: redirect('/CommITCrowd.jpg')

        get   'edit',                           to: 'home#edit', as: :users_edit
        post  'edit',                           to: 'home#update'
        delete 'authorized_applications/:id',   to: 'home#revoke', as: :authorized_applications

        get 'download', to: 'home#download'

        get 'member/payments', to: 'payments#index', as: :member_payments

        post 'mongoose', to: 'payments#add_funds'
        post 'pay_activities', to: 'payments#pay_activities'

        resources :activities, only: [:index, :show] do
          resource :participants, only: [:create, :update, :destroy]
        end
      end
    end

    root 'admin/home#index'

    # No double controllers
    get     'admin/home',   to: redirect('/')
    get     'members/home', to: redirect('/')

    # Devise routes
    devise_for :users, path: '', skip: [:registrations], controllers: {
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

    # update account with password after receiving invite
    get     'activate',     to: 'users/registrations#edit', as: :new_member_confirmation
    post    'activate',     to: 'users/registrations#update', as: :new_member_confirm

    # update password from member options
    get     'passwordchange',     to: 'users/password_change#edit', as: :password_change
    patch   'passwordchange',     to: 'users/password_change#update'

    scope module: 'public' do
      get   'status(/:token)', to: 'status#edit'
      post  'status',          to: 'status#update'
      post  'status/destroy',  to: 'status#destroy'
    end

    scope module: 'admin' do
      resources :members do
        get   'payment_whatsapp'
        patch 'force_email_change'
        post  'email/:type', to: 'members#send_email', as: :mail
        patch 'set_card_disabled/:uuid', to: 'members#set_card_disabled', as: 'set_card_disabled'

        collection do
          get 'search'
        end
      end

      resources :activities do
        resources :participants, only: [:create, :update, :destroy] do
          collection do
            post 'mail'
          end
        end
        get 'committee_members'
      end

      scope 'payments' do
        get '/', to: 'payments#index', as: "payments"
        get 'whatsapp/:member_id', to: 'payments#whatsapp_redirect', as: 'payment_whatsapp_redirect'
        get 'transactions', to: 'payments#update_transactions'
        get 'transactions_export', to: 'payments#export_payments'
      end

      resources :posts, only: [:index, :show, :create, :update, :destroy]

      resources :groups, only: [:index, :create, :show, :update, :destroy] do
        resources :group_members, only: [:create, :update, :destroy], path: 'members'
      end

      resources :settings, only: [:index, :create] do
        collection do
          get 'logs'
          patch 'profile', to: 'settings#profile'
        end
      end

      scope 'apps' do
        get 'payments',           to: 'apps#transactions', as: 'paymenthandlers'
        get 'checkout',           to: 'apps#checkout'

        # json checkout urls
        patch  'cards',           to: 'checkout_products#activate_card'
        patch  'transactions',    to: 'checkout_products#change_funds'

        resources :checkout_products, only: [:index, :show, :create, :update], path: 'products' do
          patch :flip, action: :flip_active
          match :flip, action: :flip_active, via: [:patch]
        end
      end

      # sidekiq web interface
      authenticate :user, ->(u) { u.admin? } do
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end
    end

    scope 'api' do
      use_doorkeeper do
        # skip_controllers :token_info, :applications, :authorized_applications
      end

      scope module: 'api' do
        resources :members, only: [:index, :show, :create] do
          resources :participants, only: :index
        end

        resources :groups, only: [:index, :show]

        resources :activities, only: [:index, :show] do
          resources :participants
          get 'poster'
          get 'thumbnail'
        end

        scope 'hook' do
          get 'payment/:token', to: 'webhook#payment_redirect', as: 'payment_redirect'

          post 'mollie',        to: 'webhook#mollie_hook',        as: 'mollie_hook'

          get 'mailchimp/:token', to: 'webhook#mailchimp_confirm_callback', as: 'mailchimp_confirm'
          post 'mailchimp/:token', to: 'webhook#mailchimp', as: 'mailchimp'
        end

        # NOTE: legacy implementation for checkout without oauth
        scope 'checkout' do
          get  'card',          to: 'checkout#info'
          get  'recent',        to: 'checkout#recent'
          post 'card',          to: 'checkout#create'
          get  'confirmation',  to: 'checkout#confirm'

          get  'products',      to: 'checkout#products'
          post 'transaction',   to: 'checkout#purchase'
        end

        scope 'internal' do
          get 'member_by_id',        to: 'internal#member_by_id'
          get 'member_by_studentid', to: 'internal#member_by_studentid'
        end
      end
    end
  end

  get '/', to: redirect('/404')
end

app/controllers/admin/home_controller.rb
#:nodoc:
class Admin::HomeController < ApplicationController
  def index
    @members = Member.active.count

    @studies = Education.where('status = 0').joins(:study).group('studies.code').count

    @activities = Activity.where("start_date >= ?", Date.to_date(Time.zone.today.study_year)).count

    @recentactivities = Payment.where(
      "created_at >= ?",
      Time.zone.now.beginning_of_day
    ).where(
      transaction_type: :activity,
      status: :successful
    ).take(12)

    @unpaid = Member.debtors.map(&:total_outstanding_payments).sum

    @defaulters = Member.debtors.sort_by { |debtor| -debtor.total_outstanding_payments }.take(12)
  end
end

app/controllers/admin/members_controller.rb
#:nodoc:
class Admin::MembersController < ApplicationController
  # replaced with calls in each of the methods
  # impressionist :actions => [ :create, :update ]

  def index
    if params[:search].present?
      @pagination, @members = pagy_array(Member.search(params[:search].clone))
    else
      @pagination, @members = pagy(
        Member.includes(:educations).active
          .select(:id, :first_name, :infix, :last_name, :phone_number, :email, :student_id)
          .order(:last_name, :first_name)
      )
    end
  end

  # As defined above this is an json call only
  def search
    @members = Member.select(:id, :first_name, :infix, :last_name,
                             :student_id).search(params[:search])
  end

  def show
    @member = Member.find(params[:id])

    # Show all activities from the given year + unpaid past activities.
    # And make a list of years starting from the member's join_date until the last activity
    current_year_activities = @member.activities.study_year(
      params['year']
    ).order(
      start_date: :desc
    ).joins(
      :participants
    ).distinct.where(
      participants: { reservist: false }
    )
    unpaid_old_activities = @member.unpaid_activities.order(start_date: :desc).where(
      'start_date < ?', Date.to_date(Date.today.study_year)
    )
    @activities = (current_year_activities + unpaid_old_activities).uniq

    @years = (@member.join_date.study_year..Date.today.study_year).map do |year|
      ["#{ year }-#{ year + 1 }", year]
    end.reverse

    # Pagination for checkout transactions
    @limit = params[:limit] ? params[:limit].to_i : 10

    @pagination, @transactions = pagy(CheckoutTransaction
      .where(checkout_balance: CheckoutBalance
      .find_by(member_id: params[:id]))
      .order(created_at: :desc), items: 10)
  end

  def new
    @member = Member.new

    # Construct a education so that there is always one visible to fill in
    @member.educations.build(id: '-1')
  end

  def create
    @member = Member.new(member_post_params.except('mailchimp_interests'))

    if @member.save
      unless ENV['MAILCHIMP_DATACENTER'].blank? || member_post_params[:mailchimp_interests].nil?
        MailchimpJob.perform_later(@member.email, @member,
                                   member_post_params[:mailchimp_interests].compact_blank)
      end

      @member.tags_names = params[:member][:tags_names]

      # impressionist is the logging system
      impressionist(@member, 'nieuwe lid')
      redirect_to(@member)
    else
      # If the member hasn't filled in a study, again show an empty field
      @member.educations.build(id: '-1') if @member.educations.empty?

      render('new')
    end
  end

  def edit
    @member = Member.includes(:educations).includes(:tags).find(params[:id])
    @member.educations.build(id: '-1') if @member.educations.empty?
    WebhookJob.perform_later("member", params[:id])
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_post_params.except('mailchimp_interests'))

      unless ENV['MAILCHIMP_DATACENTER'].blank? || member_post_params[:mailchimp_interests].nil?
        MailchimpJob.perform_later(@member.email, @member,
                                   member_post_params[:mailchimp_interests].compact_blank)
      end

      impressionist(@member)
      redirect_to(@member)
    else
      render('edit')
    end
  end

  def force_email_change
    @member = Member.find(params[:member_id])

    MailchimpUpdateAddressJob.perform_later(@member.email, @member.user.unconfirmed_email) unless
      @member.mailchimp_interests.nil? || ENV['MAILCHIMP_DATACENTER'].blank?

    Mailings::Devise.forced_confirm_email(@member, current_user).deliver_later
    @member.user.force_confirm_email!

    redirect_to(@member)
  end

  # Send appropriate email to user for account access, either password reset, user creation, or activation mail.
  def send_email
    @member = Member.find(params[:member_id])

    case params[:type]
    when 'create_user'
      user = User.create_on_member_enrollment!(@member)
      user.resend_confirmation!(:activation_instructions)
      flash[:success] = I18n.t('admin.member_account_status.email_sent')

    when 'resend_confirmation'
      @member.user.resend_confirmation!(:confirmation_instructions)
      flash[:success] = I18n.t('admin.member_account_status.email_sent')

    when 'password_reset'
      @member.user.send_reset_password_instructions
      flash[:success] = I18n.t('admin.member_account_status.email_sent')

    when 'consent'
      Mailings::Status.consent([@member].pluck(:id, :first_name, :infix, :last_name,
                                               :email)).deliver_later
      flash[:success] = I18n.t('admin.member_account_status.consent_sent')

    end

    redirect_to(member_path(@member))
  end

  def destroy
    @member = Member.includes(:checkout_balance).find(params[:id])

    impressionist(@member)
    flash[:notice] = []

    if @member.destroy
      flash[:notice] << I18n.t('activerecord.errors.models.member.destroy.info', name: @member.name)
      unless @member.checkout_balance.nil?
        flash[:notice] << I18n.t('activerecord.errors.models.member.destroy.checkout_emptied',
                                 balance: view_context.number_to_currency(@member.checkout_balance.balance,
                                                                          unit: '€'))
      end
      unless @member.mailchimp_interests.nil?
        flash[:notice] << I18n.t('activerecord.errors.models.member.destroy.mailchimp_queued')
      end

      redirect_to(root_url)
    else
      flash[:errors] = @member.errors.messages
      redirect_to(@member)
    end
  end

  def payment_whatsapp
    @member = Member.find(params[:member_id])
    @activities = @member.unpaid_activities.where('activities.start_date <= ?', Date.today).distinct
    @participants = @activities.map { |a| Participant.find_by(member: @member, activity: a) }
    render(layout: false, content_type: "text/plain")
  end

  def set_card_disabled
    @uuid = params[:uuid]
    @to = params[:to]
    @card = CheckoutCard.find_by(uuid: @uuid)
    @card.update(disabled: @to)
  end

  private

  def member_post_params
    params.require(:member).permit(:first_name,
                                   :infix,
                                   :last_name,
                                   :address,
                                   :house_number,
                                   :postal_code,
                                   :city,
                                   :phone_number,
                                   :emergency_phone_number,
                                   :email,
                                   :student_id,
                                   :birth_date,
                                   :join_date,
                                   :comments,
                                   tags_names: [],
                                   mailchimp_interests: [],
                                   educations_attributes: [:id, :study_id, :status, :start_date,
                                                           :end_date, :_destroy])
  end
end

app/controllers/api/members_controller.rb
#:nodoc:
class Api::MembersController < ApiController
  before_action -> { doorkeeper_authorize!('member-read') }, only: [:index, :show]

  def index
    @members = Member.all.order(:last_name,
                                :first_name).offset(params[:offset] ||= 0).limit(params[:limit] ||= 20)
  end

  # TODO: alternatief voor intro.svsticky.nl
  def create
    raise(NotImplementedError)
  end

  def show
    @member = Member.find(params[:id])
  end
end

app/controllers/members/activities_controller.rb
# The activities controller handles all actions related to enrollment for
# activities by users.
# The various methods in this controller directly manipulate Participants, a
# many-to-many association on Members, and changes made will be visible in the
# admin view. Note that the :id parameters here correspond to Activity ids, and
# not Participant ids, as this makes linking to the enrollment page for a
# single activity possible.
#:nodoc:
class Members::ActivitiesController < ApplicationController
  skip_before_action :authenticate_admin!

  layout 'members'

  # [GET] /activities
  # Renders the overview of all future activities that are enrollable.
  def index
    @member = Member.find(current_user.credentials_id)

    @activities = Activity
                  .where('(end_date IS NULL AND start_date >= ?) OR end_date >= ?',
                         Date.today, Date.today)
                  .where(is_viewable: true)
                  .order(:start_date, :start_time)

    @activities_exist = @activities.any?
    @activities = @activities.joins(:members).where(members: { id: @member.id }) if params["show"] == "registered"

    @activities = @activities.reject(&:ended?)
  end

  # [GET] /activities/:id
  # Renders the detail view of one activity, containing information about the
  # activity, the list of enrolled people and reservists, and the notes entry
  # field.
  def show
    @member = Member.find(current_user.credentials_id)
    @user = Member.find_by(email: current_user.email)
    @activity = Activity.find(params[:id])

    # Don't allow activities for old activities
    render(:unavailable, status: :gone) if @activity.ended? || !@activity.is_viewable?

    @enrollment = Participant.find_by(
      member_id: @member.id,
      activity_id: @activity.id
    )

    @attendees = @activity.ordered_attendees
    @reservists = @activity.ordered_reservists
  end
end

app/views/members/home/edit.html.haml
- content_for(:page, "edit")
- content_for(:title, @member.name)

= form_for :member, method: :post, :class => 'form-validation' do |f|

  - if @member.errors.any? || flash[:error]
    .alert.alert-danger
      %span= I18n.t('activerecord.errors.incomplete')
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg
        - if flash[:error].present?
          %li= flash[:error]

  - if flash[:notice]
    .alert.alert-success
      %span= flash[:notice]
  - if flash[:warning]
    .alert.alert-warning
      %span= flash[:warning]

  .row
    .col-xl-6
      .card
        .card-header
          %i.fa.fa-fw.fa-user
          = I18n.t('members.home.edit.general_data')
        .card-body
          .form-group
            .row
              .col-lg-4
                = f.label(:first_name)
                = f.text_field :first_name, 'value' => @member.first_name, :class => 'form-control form-control-disabled', :disabled => true
              .col-lg-3
                = f.label(:infix)
                = f.text_field :infix, :value => @member.infix, :class => 'form-control form-control-disabled', :disabled => true
              .col-lg-5
                = f.label(:last_name)
                = f.text_field :last_name, :value => @member.last_name, :class => 'form-control form-control-disabled', :disabled => true
              - if @member.birth_date?
                .col-md-6
                  = f.label(:birth_date)
                  = f.label :birth_date, :value => I18n.l(@member.birth_date), :class => 'form-control form-control-disabled'

            .callout.callout-info #{ I18n.t('members.home.edit.board_only_change_info') } #{link_to I18n.t('members.home.edit.board'), 'mailto:bestuur@svsticky.nl'}.
          %hr

          .form-group
            .row
              .col-md-8
                = f.label(:email) + "¹"
                = f.email_field :email, :value => @member.email, :class => 'form-control'

              .col-md-4
                = f.label(:language)
                = f.select :language, options_for_select([["Nederlands", :nl], ["English", :en]], selected: @user.language), {:class => 'form-control'}

          .form-group
            .row
              .col-lg-6
                = f.label(:phone_number)
                = f.telephone_field :phone_number, :value => @member.phone_number, :class => 'form-control'
              .col-lg-6
                = f.label(:emergency_phone_number) + "²"
                = f.telephone_field :emergency_phone_number, :value => @member.emergency_phone_number, :class => 'form-control'

          %hr

          .form-group
            .row
              .col-lg-8
                = f.label(:address)
                = f.text_field :address, :value => @member.address, :class => 'form-control'
              .col-lg-4
                = f.label(:house_number)
                = f.text_field :house_number, :value => @member.house_number, :class => 'form-control'

          .form-group
            .row
              .col-lg-6
                = f.label(:postal_code)
                = f.text_field :postal_code, :value => @member.postal_code, :class => 'form-control'
              .col-lg-6
                = f.label(:city)
                = f.text_field :city, :value => @member.city, :class => 'form-control'

          %hr

          .footnote
            %span.footnote 1
            .help-block= I18n.t('activerecord.annotations.member.email')

          .footnote
            %span.footnote 2
            .help-block
              = I18n.t('members.home.edit.underage_phone')

          .footnote
            %span.footnote 3
            .help-block ctf_41317555

    - if !ENV['MAILCHIMP_DATACENTER'].blank?
      .col-xl-6
        .card
          .card-header
            %i.fa.fa-fw.fa-envelope
            = I18n.t(:mailinglists, scope: 'activerecord.annotations.member')
          .card-body
            .form-group
              - if !@member.mailchimp_interests.nil? && @member.active?
                - Rails.configuration.mailchimp_interests.each do |name, key|
                  .row
                    .col-md-12
                      %label.ui-checkbox
                        = f.check_box "mailchimp_interests[#{key}]", :checked => @member.mailchimp_interests[key]
                        %span= I18n.t("#{name}.name", scope: 'activerecord.annotations.member')
                        .callout.callout-info= I18n.t("#{name}.description", scope: 'activerecord.annotations.member')
              - if !@member.enrolled_in_study?
                - Rails.configuration.mailchimp_interests_alumni.each do |name, key|
                  .row
                    .col-md-12
                      %label.ui-checkbox
                        = f.check_box "mailchimp_interests[#{key}]", :checked => (!@member.mailchimp_interests.nil? ? @member.mailchimp_interests[key] : false)
                        %span= I18n.t("#{name}.name", scope: 'activerecord.annotations.member')
                        .callout.callout-info= I18n.t("#{name}.description", scope: 'activerecord.annotations.member')

    .col-xl-6
      .card
        .card-header
          %i.fa.fa-fw.fa-graduation-cap
          = I18n.t 'members.home.edit.study'
        .card-body
          .form-group
            .row
              .col-md-6
                = f.label(:student_id)
                = f.text_field :student_id, :value => @member.student_id, :class => 'form-control form-control-disabled', :disabled => true
              .col-md-6
                = f.label(:join_date)
                = f.text_field :join_date, :value => I18n.l(@member.join_date), :class => 'form-control form-control-disabled', :disabled => true

          %hr

          .form-group
            %label{for: 'member_educations'}
              = I18n.t('activerecord.attributes.member.educations')

          %table.table.table-striped
            %tbody
              - @member.educations.each do |education|
                - if education.study.code?
                  = f.fields_for 'educations_attributes[]', education do |fs|
                    %tr
                      %td= I18n.t(education.study.code.downcase, scope: 'activerecord.attributes.study.names')

                      %td.dropdown
                        - if education.status == 'active'
                          = fs.hidden_field :id

                        .ui-select
                          - if education.status == 'active'
                            = fs.select :status, options_for_select( [:active, :graduated, :stopped].map{ |name| [I18n.t(name, scope: 'activerecord.attributes.education.status').downcase, name] }, education.status )
                          - else
                            %span
                              = I18n.t(education.status, scope: 'activerecord.attributes.education.status').downcase

          - if @member.educations.any? { |education| education.status == 'active' }
            .callout.callout-info
              = I18n.t('members.home.edit.edit_study_info')
              %br
              %br
              #{ I18n.t('members.home.edit.mutate_study') } #{link_to I18n.t('members.home.edit.board'), 'mailto:bestuur@svsticky.nl'}.

      .card
        .card-header
          %i.fa.fa-fw.fa-gavel
          = I18n.t 'members.home.edit.privacy_panel.header'
        .card-body
          = I18n.t 'members.home.edit.privacy_panel.view'
          = link_to 'https://public.svsticky.nl/privacystatement.pdf' do
            = I18n.t 'members.home.edit.privacy_panel.privacy_statement'

  - if @applications.any?
    .col-xl-6
      .card
        .card-header
          %i.fa.fa-fw.fa-rocket
          = I18n.t("members.home.edit.externe_applicaties")
        %table.table.table-striped.table-linked
          - @applications.each do |application|
            %tr
              %td= application.name
              %td= I18n.l application.created_at
              %td
                = link_to authorized_applications_path(application), 'data-method' => :delete do
                  = I18n.t("members.home.edit.revoke")

  .row
    .col-xl-12
      .card
        .card-body
          .btn-group
            %button.btn.btn-success{type: 'submit'}
              = I18n.t("editing.save")
            = link_to I18n.t("editing.cancel"), users_root_path, { :class => 'button btn btn-secondary' }

          .btn-group.float-right
            = link_to password_change_path, { :class => 'button btn btn-warning' } do
              %i.fa.fa-key
              = I18n.t 'members.home.edit.password_options.change_password'

            = link_to download_path, { :class => 'button btn btn-secondary', :download => I18n.t('members.home.index.personal_data') } do
              %i.fa.fa-download
              = I18n.t 'members.home.index.personal_data'

app/views/members/home/fetch_activities.js.erb
document.querySelector("#activity_list").innerHTML = "<%= escape_javascript(render partial: 'members/home/partials/activity_list', locals: { member: @member, participants: @participants } ) %>"

app/views/members/home/index.html.haml
- content_for(:page, 'home')

.row
  .col-md-6
    #posts
      - @posts.each do |post|
        .card
          .card-header{class: ('avatar-padding' if post.author.avatar.attached?)}
            %h3= post.title

            .card-img-overlay
              - if post.pinned?
                %span.ribbon
                  %i.service-icon.fa.fa-map-pin

            .post-info
              - if post.author.avatar.attached?
                = image_tag post.author.avatar_representation, class: 'avatar'
              %h4= post.author.name
              %ul
                %li= I18n.l(post.published_at, format: "%H:%M - %d %B %Y")
                - post.tags&.each do |tag|
                  %li= tag
          .card-body.content
            = raw post.content

    = render partial: 'layouts/partials/pagination', locals: {pagy: @pagination}

  .col-lg-6.float-right
    -# - unless @balance.blank?
    -#   .card.card-box
    -#     .row.no-gutters
    -#       .col.bg-success.card-body
    -#         %i.fa.fa-shopping-cart.fa-5x
    -#       .col.card-body
    -#         %p.size-h2
    -#           = number_to_currency( @balance.balance, :unit => '€' )
    -#         %p.text-muted.text-center= I18n.t('activerecord.models.checkout_balance')

    .card.card-box
      .row.no-gutters
        .col.card-body
          %p.size-h2
            = number_to_currency( @debt, :unit => '€' )
          %p.text-muted.text-center= I18n.t('members.home.index.outstanding_payments')
        .col.bg-warning.card-body
          %i.fa.fa-ticket-alt.fa-5x

    - if @member.groups.any?
      .widget
        .card
          .card-header
            %i.fa.fa-fw.fa-users
            = I18n.t('activerecord.models.group')
          %table.table.card-body
            %tbody
              - @member.groups.each do |group|
                %tr
                  %td
                    %strong
                      = group[ :name ]
                  %td= Date.years( group[ :years ].sort )

                  %td
                    - group[ :positions ].each do |position|
                      - position.each do |position, year|
                        - unless position.nil?
                          %span{class: year == Date.today.study_year ? "font-weight-bold" : ""
                            }= I18n.t(position,
                                      scope: 'activerecord.attributes.group.positions',
                                      default: position.capitalize)


    .card
      .card-header
        %span
          %i.fa.fa-fw.fa-fw.fa-ticket-alt
          = I18n.t("navigation.activity")
          = select_tag :year, options_for_select( @years, params['year'] ), class: 'year-selector'
      %table.table.table-striped
        %tbody
          - @participants.each do |activity|
            %tr{ :class => ('red' unless activity.currency(@member).nil? || activity.currency(@member) == 0 || activity.participants.where(:member => @member).first.paid)}
              - if !activity.ended?
                %td= link_to activity.name, activity_path(activity)
              - else
                %td= activity.name

              - if !activity.start_date.nil?
                %td.hidden-xs
                  - if activity.end_date.nil?
                    = I18n.l activity.start_date
                  - else
                    #{I18n.l activity.start_date} - #{I18n.l activity.end_date}
              - if !activity.currency(@member).nil?
                %td= number_to_currency(activity.currency(@member), :unit => '€')
              - else
                %tdl
              %td.text-center.d-none.d-sm-block
                - if !activity.currency(@member).nil? && activity.currency(@member) > 0
                  - if activity.participants.where(:member => @member).first.paid
                    %span.label.label-success= I18n.t('activerecord.attributes.participant.paid.true')
                  - else
                    %span.label.label-warning= I18n.t('activerecord.attributes.participant.paid.false')
    -# .card
    -#   .card-header
    -#     %i.fa.fa-fw.fa-fw.fa-shopping-cart
    -#     %span= I18n.t("activerecord.models.checkout_transactions")
    -#   %table.table.card-body
    -#     %tbody
    -#       - @transactions.each do |transaction|
    -#         %tr
    -#           %td.d-block.d-sm-none{ :colspan => 2 }= I18n.l transaction.created_at
    -#           %td.d-none.d-sm-table-cell= I18n.l transaction.created_at
    -#           %td.d-none.d-sm-table-cell= transaction.products
    -#           %td
    -#             = number_to_currency(transaction.price, :unit => '€')
    -#             - if transaction.price > 0
    -#               %span.fa.fa-sort-asc.float-right
    -#             - else
    -#               %span.fa.fa-sort-desc.float-right