config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper_openid_connect

  constraints subdomain: ['wordlid', 'wordlid.dev', 'signup', 'signup.dev', 'join', 'join.dev'] do
    scope module: 'public' do
      get  '/', to: 'home#index', as: 'public'
      post '/', to: 'home#create'
    end
  end

  constraints subdomain: ['koala', 'koala.dev', 'leden', 'leden.dev', 'members', 'members.dev'] do
    authenticate :user, ->(u) { !u.admin? } do
      scope module: 'members' do
        root to: 'home#index', as: :users_root

        get '/activities/69420', to: redirect('/CommITCrowd.jpg')

        get   'edit',                           to: 'home#edit', as: :users_edit
        post  'edit',                           to: 'home#update'
        delete 'authorized_applications/:id',   to: 'home#revoke', as: :authorized_applications

        get 'download', to: 'home#download'

        get 'member/payments', to: 'payments#index', as: :member_payments

        post 'mongoose', to: 'payments#add_funds'
        post 'pay_activities', to: 'payments#pay_activities'

        resources :activities, only: [:index, :show] do
          resource :participants, only: [:create, :update, :destroy]
        end
      end
    end

    root 'admin/home#index'

    # No double controllers
    get     'admin/home',   to: redirect('/')
    get     'members/home', to: redirect('/')

    # Devise routes
    devise_for :users, path: '', skip: [:registrations], controllers: {
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

    # update account with password after receiving invite
    get     'activate',     to: 'users/registrations#edit', as: :new_member_confirmation
    post    'activate',     to: 'users/registrations#update', as: :new_member_confirm

    # update password from member options
    get     'passwordchange',     to: 'users/password_change#edit', as: :password_change
    patch   'passwordchange',     to: 'users/password_change#update'

    scope module: 'public' do
      get   'status(/:token)', to: 'status#edit'
      post  'status',          to: 'status#update'
      post  'status/destroy',  to: 'status#destroy'
    end

    scope module: 'admin' do
      resources :members do
        get   'payment_whatsapp'
        patch 'force_email_change'
        post  'email/:type', to: 'members#send_email', as: :mail
        patch 'set_card_disabled/:uuid', to: 'members#set_card_disabled', as: 'set_card_disabled'

        collection do
          get 'search'
        end
      end

      resources :activities do
        resources :participants, only: [:create, :update, :destroy] do
          collection do
            post 'mail'
          end
        end
        get 'committee_members'
      end

      scope 'payments' do
        get '/', to: 'payments#index', as: "payments"
        get 'whatsapp/:member_id', to: 'payments#whatsapp_redirect', as: 'payment_whatsapp_redirect'
        get 'transactions', to: 'payments#update_transactions'
        get 'transactions_export', to: 'payments#export_payments'
      end

      resources :posts, only: [:index, :show, :create, :update, :destroy]

      resources :groups, only: [:index, :create, :show, :update, :destroy] do
        resources :group_members, only: [:create, :update, :destroy], path: 'members'
      end

      resources :settings, only: [:index, :create] do
        collection do
          get 'logs'
          patch 'profile', to: 'settings#profile'
        end
      end

      scope 'apps' do
        get 'payments',           to: 'apps#transactions', as: 'paymenthandlers'
        get 'checkout',           to: 'apps#checkout'

        # json checkout urls
        patch  'cards',           to: 'checkout_products#activate_card'
        patch  'transactions',    to: 'checkout_products#change_funds'

        resources :checkout_products, only: [:index, :show, :create, :update], path: 'products' do
          patch :flip, action: :flip_active
          match :flip, action: :flip_active, via: [:patch]
        end
      end

      # sidekiq web interface
      authenticate :user, ->(u) { u.admin? } do
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end
    end

    scope 'api' do
      use_doorkeeper do
        # skip_controllers :token_info, :applications, :authorized_applications
      end

      scope module: 'api' do
        resources :members, only: [:index, :show, :create] do
          resources :participants, only: :index
        end

        resources :groups, only: [:index, :show]

        resources :activities, only: [:index, :show] do
          resources :participants
          get 'poster'
          get 'thumbnail'
        end

        scope 'hook' do
          get 'payment/:token', to: 'webhook#payment_redirect', as: 'payment_redirect'

          post 'mollie',        to: 'webhook#mollie_hook',        as: 'mollie_hook'

          get 'mailchimp/:token', to: 'webhook#mailchimp_confirm_callback', as: 'mailchimp_confirm'
          post 'mailchimp/:token', to: 'webhook#mailchimp', as: 'mailchimp'
        end

        # NOTE: legacy implementation for checkout without oauth
        scope 'checkout' do
          get  'card',          to: 'checkout#info'
          get  'recent',        to: 'checkout#recent'
          post 'card',          to: 'checkout#create'
          get  'confirmation',  to: 'checkout#confirm'

          get  'products',      to: 'checkout#products'
          post 'transaction',   to: 'checkout#purchase'
        end

        scope 'internal' do
          get 'member_by_id',        to: 'internal#member_by_id'
          get 'member_by_studentid', to: 'internal#member_by_studentid'
        end
      end
    end
  end

  get '/', to: redirect('/404')
end

app/models/settings.rb
class Settings < RailsSettings::Base
end

app/controllers/admin/settings_controller.rb
#:nodoc:
class Admin::SettingsController < ApplicationController
  respond_to :json, only: [:create, :destroy]

  def index
    @admin = current_user.credentials
    @user = User.find_by(email: current_user.email)

    @studies = Study.all

    @applications = Doorkeeper::Application.all
  end

  def create
    if ['additional_positions.moot', 'additional_positions.committee'].include?(params[:setting])
      Settings[params[:setting]] = params[:value].downcase.split(',').each(&:strip!)

    elsif ['intro.membership', 'intro.activities'].include?(params[:setting])
      Settings[params[:setting]] =
        Activity.where(id: params[:value].split(',').map(&:to_i)).collect(&:id)

      render(status: :ok, json: {
               activities: Settings[params[:setting]],
               warning: params[:value].split(',').map(&:to_i).count != Settings[params[:setting]].count
             })
      return
    elsif %w[mongoose_ideal_costs].include?(params[:setting])
      head(:bad_request) && return if (params[:value] =~ /\d{1,}[,.]\d{2}/).nil?

      Settings[params[:setting]] = params[:value].sub(',', '.').to_f
    elsif ['begin_study_year'].include?(params[:setting])
      head(:bad_request) && return if (params[:value] =~ /\d{4}-\d{2}-\d{2}/).nil?

      Settings[params[:setting]] = Date.parse(params[:value])
    elsif ['liquor_time'].include?(params[:setting])
      head(:bad_request) && return if (params[:value] =~ /\d{2}:\d{2}/).nil?

      Settings[params[:setting]] = params[:value]
    elsif %w[ideal_relation_code payment_condition_code mongoose_ledger_number
             accountancy_ledger_number].include?(params[:setting])
      head(:bad_request) && return if (params[:value] =~ /\d+/).nil?

      Settings[params[:setting]] = params[:value]
    elsif ['accountancy_cost_location'].include?(params[:setting])
      Settings[params[:setting]] = params[:value]
    end
    head(:ok)
    return
  end

  def profile
    @user = User.find_by(email: current_user.email)
    @user.update(user_post_params)

    @admin = Admin.find(current_user.credentials_id)
    @admin.update(admin_post_params)

    return redirect_to(request.referer, notice: I18n.t("activerecord.errors.info"))
  end

  def logs
    @limit = params[:limit] ? params[:limit].to_i : 50

    @pagination, @impressions = pagy(Impression.all.order(created_at: :desc),
                                     items: params[:limit] ||= 50)
    @total_log_items = Impression.count
  end

  private

  def admin_post_params
    params.require(:admin).permit(:first_name, :infix, :last_name, :signature, :avatar)
  end

  def user_post_params
    params.require(:admin).permit(:language)
  end
end

app/views/admin/settings/index.html.haml
- content_for(:page, 'settings')
- content_for(:title, I18n.t('admin.navigation.settings'))

%section#content

  .page.page-form{ :data => { 'authenticity_token' => form_authenticity_token}}

    - if @admin.errors.any?
      .alert.alert-danger
        %span= I18n.t('activerecord.errors.incomplete')
        %ul
          - @admin.errors.full_messages.each do |msg|
            %li= msg

    - if flash[:notice]
      .alert.alert-success
        %span= flash[:notice]

    .row
      .col-md-6
        .card
          .card-header
            %i.fas.fa-fw.fa-wrench
            = I18n.t('admin.navigation.settings')
          %ul.list-group#settings
            = form_tag settings_url do

              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'begin_study_year.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'begin_study_year.description', scope: 'activerecord.attributes.settings'

                  .col-md-6
                    %input.form-control{ :id => 'options_begin_study_year', :name => 'begin_study_year', :value => Settings.begin_study_year, :placeholder => 'yyyy-mm-dd' }

              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'intro_membership.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'intro_membership.description', scope: 'activerecord.attributes.settings'

                  .col-md-6
                    %input.form-control{ :id => 'options_intro_membership', :name => 'intro.membership', :value => Settings['intro.membership'].join(', ') }

              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'intro_activities.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'intro_activities.description', scope: 'activerecord.attributes.settings'

                  .col-md-6
                    %input.form-control{ :id => 'options_intro_activities', :name => 'intro.activities', :value => Settings['intro.activities'].join(', '), :placeholder => I18n.t('admin.settings.separate') }

              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'additional_committee_positions.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'additional_committee_positions.description', scope: 'activerecord.attributes.settings'

                  .col-md-6
                    %input.form-control{ :id => 'options_additional_committee_positions', :name => 'additional_positions.committee', :value =>Settings['additional_positions.committee'].join(', '), :placeholder => I18n.t('admin.settings.separate') }

              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'additional_moot_positions.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'additional_moot_positions.description', scope: 'activerecord.attributes.settings'

                  .col-md-6
                    %input.form-control{ :id => 'options_additional_moot_positions', :name => 'additional_positions.moot', :value => Settings['additional_positions.moot'].join(', '), :placeholder => I18n.t('admin.settings.separate') }
              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'mongoose_ideal_costs.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'mongoose_ideal_costs.description', scope: 'activerecord.attributes.settings'

                  .col-md-6
                    %input.form-control{ :id => 'options_mongoose_ideal_costs', :name => 'mongoose_ideal_costs', :value => Settings.mongoose_ideal_costs, :placeholder => '' }
              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'ideal_relation_code.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'ideal_relation_code.description', scope: 'activerecord.attributes.settings'
                  .col-md-6
                    %input.form-control{ :id => 'options_ideal_relation_code', :name => 'ideal_relation_code', :value => Settings.ideal_relation_code, :placeholder => '' }
              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'payment_condition_code.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'payment_condition_code.description', scope: 'activerecord.attributes.settings'
                  .col-md-6
                    %input.form-control{ :id => 'options_payment_condition_code', :name => 'payment_condition_code', :value => Settings.payment_condition_code, :placeholder => '' }
              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'accountancy_ledger_number.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'accountancy_cost_location.description', scope: 'activerecord.attributes.settings'
                  .col-md-6
                    %input.form-control{ :id => 'options_accountancy_ledger_number', :name => 'accountancy_ledger_number', :value => Settings.accountancy_ledger_number, :placeholder => '' }
              %li.list-group-item
                .container.row
                  .col-md-6
                    %b= I18n.t 'accountancy_cost_location.name', scope: 'activerecord.attributes.settings'
                    %p= I18n.t 'accountancy_cost_location.description', scope: 'activerecord.attributes.settings'
                  .col-md-6
                    %input.form-control{ :id => 'options_accountancy_cost_location', :name => 'accountancy_cost_location', :value => Settings.accountancy_cost_location, :placeholder => '' }


      .col-md-6
        = form_for :admin, :url => profile_settings_path, method: :patch, :html => { :class => 'form-validation signature' } do |f|
          .card
            .card-header
              %i.fa.fa-fw.fa-user
              = I18n.t('admin.settings.admin_title')
            .card-body
              = f.hidden_field :id, :value => @admin.id, :class => 'id'

              .form-group
                .row
                  .col-md-4
                    %label{for: ''}
                    = I18n.t('admin.members.name')
                    = f.text_field :first_name, :value => @admin.first_name, :class => 'form-control'
                  .col-md-5
                    %label{for: ''}
                    = I18n.t('admin.members.infix')
                    = f.text_field :infix, :value => @admin.infix, :class => 'form-control'
                  .col-md-7
                    %label{for: ''}
                    = I18n.t('admin.members.surname')
                    = f.text_field :last_name, :value => @admin.last_name, :class => 'form-control'

              .form-group
                .row
                  .col-md-12
                    %label{for: ''}
                    = I18n.t('activerecord.attributes.member.language')
                    = f.select :language, options_for_select([["Nederlands", :nl], ["English", :en]], selected: @user.language)

                .row
                  .col-lg-12.avatar-view
                    = label(:admin, :avatar)
                    .image-group
                      - if @admin.avatar.attached?
                        = image_tag @admin.avatar, class: 'preview-avatar avatar'

                    .image-side
                      .input-group
                        %input#output.form-control{ :readonly => '', :value => ("#{@admin.avatar.filename}" if @admin.avatar.attached?) }

                        .input-group-append
                          .btn.btn-primary.file-input-wrapper
                            %span
                              = I18n.t('files.upload')
                            = f.file_field :avatar, { 'data-ui-file-upload' => '' }
                        .input-group-append
                          %button.btn.btn-primary.dropdown-toggle{ 'data-toggle' => 'dropdown', :type => 'button', :class => ( 'disabled' unless @admin.avatar.attached? ) }
                            %span.caret
                          %ul.dropdown-menu
                            %li
                              - if @admin.avatar.attached?
                                = link_to 'Download', @admin.avatar, :download => '', :class => 'dropdown-item'
                            %li.divider
                            %li
                              = link_to I18n.t('files.delete'), '#', :class => 'dropdown-item remove'

              .form-group#mail
                %label{for: ''}
                = I18n.t('admin.settings.signature')
                = f.hidden_field :signature, :class => 'form-control', :id => 'html'

                #editor
                  != @admin.signature

              %button.btn.btn-success{type: 'submit'}
                = I18n.t('editing.save')

        .card
          .card-header
            %i.fa.fa-fw.fa-rocket
            = I18n.t('admin.settings.external_apps')
          %table.table.table-striped.table-linked
            - @applications.each do |application|
              %tr
                %td= link_to application.name, application.redirect_uri
                %td= application.redirect_uri

app/views/admin/settings/logs.html.haml
- content_for(:page, 'settings')
- content_for(:subpage, 'logs')
- content_for(:title, "#{I18n.t('admin.navigation.settings')} | #{I18n.t('admin.navigation.impressions')}")

%section#content

  .page.page-table
    %section.card.table-dynamic
      .table-responsive
        %table.table.table-bordered.table-striped
          %thead
            %tr
              %th
                .th
                  = I18n.t('admin.settings.date')
                  -#
                    %span.glyphicon.glyphicon-chevron-up
                    %span.glyphicon.glyphicon-chevron-down
              %th
                .th
                  = I18n.t('admin.settings.user')
              %th
                .th
                  = I18n.t('admin.settings.object')
                  -#
                    %span.glyphicon.glyphicon-chevron-up
                    %span.glyphicon.glyphicon-chevron-down
              %th
                .th
                  = I18n.t('admin.settings.action')
              %th
                .th
                  = I18n.t('admin.settings.address')

          - @impressions.each do |impression|
            %tr
              %td= I18n.l impression.created_at
              %td
                - if !impression.user_id.nil? && User.exists?(impression.user_id)
                  = User.find( impression.user_id ).email
              %td
                - if ['Member', 'Group', 'Activity'].include? impression.impressionable_type
                  - if impression.impressionable.nil? && !impression.message.nil?
                    = impression.message
                  - elsif !impression.impressionable.nil?
                    = link_to impression.impressionable.name, impression.impressionable

                - elsif 'Participant' == impression.impressionable_type && impression.impressionable_id
                  = link_to impression.impressionable.activity.name, impression.impressionable.activity, :class => 'inline'

                  - if impression.impressionable.member.present?
                    = link_to impression.impressionable.member.name, impression.impressionable.member, :class => 'inline'

                - elsif 'GroupMember' == impression.impressionable_type
                  = link_to impression.impressionable.group.name, impression.impressionable.group, :class => 'inline'

                  - if impression.impressionable.member.present?
                    = link_to impression.impressionable.member.name, impression.impressionable.member, :class => 'inline'
                - elsif impression.message
                  = impression.controller_name + ": " + impression.message
                - else
                  = impression.controller_name

              %td
                - if !impression.message.nil?
                  - if impression.impressionable_type == 'Participant'
                    - if impression.impressionable_id.nil?
                      = impression.message

                    - elsif impression.action_name == 'update'
                      = I18n.t impression.message, scope: [ :activerecord, :attributes, :impression, impression.impressionable_type.downcase, impression.action_name]

                    - else
                      = I18n.t impression.action_name, scope: [ :activerecord, :attributes, :impression, impression.impressionable_type.downcase], message: impression.message

                  - else
                    = impression.action_name + ": " + impression.message

                - else
                  - if impression.impressionable_type == 'Group' && !impression.impressionable.nil?
                    = I18n.t impression.action_name, scope: [ :activerecord, :attributes, :impression, impression.impressionable_type.downcase], category: "#{I18n.t impression.impressionable.category, scope: [ :activerecord, :attributes, :group, :categories]}"

                  - elsif impression.impressionable_type == 'GroupMember'
                    = I18n.t impression.action_name, scope: [ :activerecord, :attributes, :impression, impression.impressionable_type.downcase], name: "#{I18n.t impression.impressionable.group.category, scope: [ :activerecord, :attributes, :group, :members]}".downcase, position: "#{I18n.t impression.impressionable.position, scope: [ :activerecord, :attributes, :group, :positions]}".downcase
                  - else
                    = I18n.t impression.action_name, scope: [ :activerecord, :attributes, :impression, impression.impressionable_type.downcase]

              %td= impression.ip_address

      .card-footer
        = render partial: 'layouts/partials/pagination', locals: {pagy: @pagination}