config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper_openid_connect

  constraints subdomain: ['wordlid', 'wordlid.dev', 'signup', 'signup.dev', 'join', 'join.dev'] do
    scope module: 'public' do
      get  '/', to: 'home#index', as: 'public'
      post '/', to: 'home#create'
    end
  end

  constraints subdomain: ['koala', 'koala.dev', 'leden', 'leden.dev', 'members', 'members.dev'] do
    authenticate :user, ->(u) { !u.admin? } do
      scope module: 'members' do
        root to: 'home#index', as: :users_root

        get '/activities/69420', to: redirect('/CommITCrowd.jpg')

        get   'edit',                           to: 'home#edit', as: :users_edit
        post  'edit',                           to: 'home#update'
        delete 'authorized_applications/:id',   to: 'home#revoke', as: :authorized_applications

        get 'download', to: 'home#download'

        get 'member/payments', to: 'payments#index', as: :member_payments

        post 'mongoose', to: 'payments#add_funds'
        post 'pay_activities', to: 'payments#pay_activities'

        resources :activities, only: [:index, :show] do
          resource :participants, only: [:create, :update, :destroy]
        end
      end
    end

    root 'admin/home#index'

    # No double controllers
    get     'admin/home',   to: redirect('/')
    get     'members/home', to: redirect('/')

    # Devise routes
    devise_for :users, path: '', skip: [:registrations], controllers: {
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

    # update account with password after receiving invite
    get     'activate',     to: 'users/registrations#edit', as: :new_member_confirmation
    post    'activate',     to: 'users/registrations#update', as: :new_member_confirm

    # update password from member options
    get     'passwordchange',     to: 'users/password_change#edit', as: :password_change
    patch   'passwordchange',     to: 'users/password_change#update'

    scope module: 'public' do
      get   'status(/:token)', to: 'status#edit'
      post  'status',          to: 'status#update'
      post  'status/destroy',  to: 'status#destroy'
    end

    scope module: 'admin' do
      resources :members do
        get   'payment_whatsapp'
        patch 'force_email_change'
        post  'email/:type', to: 'members#send_email', as: :mail
        patch 'set_card_disabled/:uuid', to: 'members#set_card_disabled', as: 'set_card_disabled'

        collection do
          get 'search'
        end
      end

      resources :activities do
        resources :participants, only: [:create, :update, :destroy] do
          collection do
            post 'mail'
          end
        end
        get 'committee_members'
      end

      scope 'payments' do
        get '/', to: 'payments#index', as: "payments"
        get 'whatsapp/:member_id', to: 'payments#whatsapp_redirect', as: 'payment_whatsapp_redirect'
        get 'transactions', to: 'payments#update_transactions'
        get 'transactions_export', to: 'payments#export_payments'
      end

      resources :posts, only: [:index, :show, :create, :update, :destroy]

      resources :groups, only: [:index, :create, :show, :update, :destroy] do
        resources :group_members, only: [:create, :update, :destroy], path: 'members'
      end

      resources :settings, only: [:index, :create] do
        collection do
          get 'logs'
          patch 'profile', to: 'settings#profile'
        end
      end

      scope 'apps' do
        get 'payments',           to: 'apps#transactions', as: 'paymenthandlers'
        get 'checkout',           to: 'apps#checkout'

        # json checkout urls
        patch  'cards',           to: 'checkout_products#activate_card'
        patch  'transactions',    to: 'checkout_products#change_funds'

        resources :checkout_products, only: [:index, :show, :create, :update], path: 'products' do
          patch :flip, action: :flip_active
          match :flip, action: :flip_active, via: [:patch]
        end
      end

      # sidekiq web interface
      authenticate :user, ->(u) { u.admin? } do
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end
    end

    scope 'api' do
      use_doorkeeper do
        # skip_controllers :token_info, :applications, :authorized_applications
      end

      scope module: 'api' do
        resources :members, only: [:index, :show, :create] do
          resources :participants, only: :index
        end

        resources :groups, only: [:index, :show]

        resources :activities, only: [:index, :show] do
          resources :participants
          get 'poster'
          get 'thumbnail'
        end

        scope 'hook' do
          get 'payment/:token', to: 'webhook#payment_redirect', as: 'payment_redirect'

          post 'mollie',        to: 'webhook#mollie_hook',        as: 'mollie_hook'

          get 'mailchimp/:token', to: 'webhook#mailchimp_confirm_callback', as: 'mailchimp_confirm'
          post 'mailchimp/:token', to: 'webhook#mailchimp', as: 'mailchimp'
        end

        # NOTE: legacy implementation for checkout without oauth
        scope 'checkout' do
          get  'card',          to: 'checkout#info'
          get  'recent',        to: 'checkout#recent'
          post 'card',          to: 'checkout#create'
          get  'confirmation',  to: 'checkout#confirm'

          get  'products',      to: 'checkout#products'
          post 'transaction',   to: 'checkout#purchase'
        end

        scope 'internal' do
          get 'member_by_id',        to: 'internal#member_by_id'
          get 'member_by_studentid', to: 'internal#member_by_studentid'
        end
      end
    end
  end

  get '/', to: redirect('/404')
end

app/views/layouts/partials/_editor.html.haml
.ui-editor.ta-root.focussed
  .ta-toolbar.btn-toolbar.focussed

    .btn-group
      %button.btn.btn-default{name: 'bold', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-bold
      %button.btn.btn-default{name: 'italic', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-italic
      %button.btn.btn-default{name: 'underline', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-underline
      %button.btn.btn-default{name: 'strikethrough', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-strikethrough

    .btn-group
      %button.btn.btn-default.dropdown-toggle{ 'data-toggle' => 'dropdown', tabindex: '-1', type: 'button', unselectable: 'on' }
        %i.fa.fa-font
        %span.caret

      %ul.dropdown-menu
        %li{ :style => 'font-family: arial;' }
          %a.dropdown-item.font-family{name: 'arial', tabindex: '-1', type: 'button', unselectable: 'on'}
            Arial
        %li{ :style => 'font-family: georgia;' }
          %a.dropdown-item.font-family{name: 'georgia', tabindex: '-1', type: 'button', unselectable: 'on'}
            Georgia
        %li{ :style => 'font-family: verdana;' }
          %a.dropdown-item.font-family{name: 'verdana', tabindex: '-1', type: 'button', unselectable: 'on'}
            Verdana
        %li{ :style => 'font-family: tahoma;' }
          %a.dropdown-item.font-family{name: 'tahoma', tabindex: '-1', type: 'button', unselectable: 'on'}
            Tahoma
        %li{ :style => 'font-family: Comic sans ms;' }
          %a.dropdown-item.font-family{name: 'comic sans', tabindex: '-1', type: 'button', unselectable: 'on'}
            Comic sans

    .btn-group
      %button.btn.btn-default.dropdown-toggle{ 'data-toggle' => 'dropdown', tabindex: '-1', type: 'button', unselectable: 'on' }
        %i.fa.fa-text-height
        %span.caret

      %ul.dropdown-menu
        %li.dropdown-item{ :style => 'font-size: 0.8em;' }
          %a.font-size{name: 'small', tabindex: '-1', type: 'button', unselectable: 'on'}
            = I18n.t('layouts.partials.editor.small')
        %li.dropdown-item{ :style => 'font-size: 1em;' }
          %a.font-size{name: 'medium', tabindex: '-1', type: 'button', unselectable: 'on'}
            = I18n.t('layouts.partials.editor.standard')
        %li.dropdown-item{ :style => 'font-size: 1.2em;' }
          %a.font-size{name: 'large', tabindex: '-1', type: 'button', unselectable: 'on'}
            = I18n.t('layouts.partials.editor.large')

    .btn-group
      %button.btn.btn-default{name: 'ol', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-list-ol
      %button.btn.btn-default{name: 'ul', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-list-ul

    .btn-group
      %button.btn.btn-default{name: 'left', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-align-left
      %button.btn.btn-default{name: 'center', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-align-center
      %button.btn.btn-default{name: 'right', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-align-right

    .btn-group
      %button.btn.btn-default{name: 'erase', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-eraser

    .btn-group.float-right{ :style => 'margin-right: 0px; '}
      %button.btn.btn-default{name: 'html', tabindex: '-1', type: 'button', unselectable: 'on'}
        %i.fa.fa-code

app/views/layouts/partials/_footer.html.haml
%footer.w-full.h-16.p-2.bg-gray-800
  .container.flex.justify-center
    .flex.m-auto.justify-center{ :class => "sm:w-1/3" }
      = link_to image_tag('//public.svsticky.nl/logos/hoofd_outline_wit.svg', {:style => 'height: 40px; width: 40px;'}), '//svsticky.nl', :target => '_blank'
      .my-auto.flex.flex-col.md:flex-row
        = link_to '//svsticky.nl/vereniging/over-ons', :target => '_blank' do
          %span.text-white.px-2.align-middle
            = I18n.t(:about_us, scope: 'footer')
        = link_to '//svsticky.nl/vereniging/contact', :target => '_blank' do
          %span.text-white.px-2.align-middle
            = I18n.t(:contact, scope: 'footer')

    .flex.m-auto.justify-center{ :class => "sm:w-1/3" }
      = link_to '//www.facebook.com/stickyutrecht', :target => '_blank' do
        %i.fab.fa-facebook-f.fa-lg.text-white.px-2.align-middle
      = link_to '//www.linkedin.com/company/1125476', :target => '_blank' do
        %i.fab.fa-linkedin-in.fa-lg.text-white.px-2.align-middle
      = link_to '//www.github.com/svsticky', :target => '_blank' do
        %i.fab.fa-github.fa-lg.text-white.px-2.align-middle

    .flex.m-auto.justify-center{ :class => "sm:w-1/3" }
      - if I18n.locale == :nl
        = link_to '//public.svsticky.nl/privacystatement.pdf', :target => '_blank' do
          %span.text-white.px-2.align-middle
            = I18n.t(:privacy, scope: 'footer')
      - else
        = link_to '//public.svsticky.nl/privacystatement_english.pdf', :target => '_blank' do
          %span.text-white.px-2.align-middle
            = I18n.t(:privacy, scope: 'footer')

app/views/layouts/partials/_mail.html.haml
-#
  @param {integer}  id            - Id of the activity
  @param {?}        recipients    - List of members for name and email
  @param {string}   subject
  @param {string}   mail          - Name of the template used in this mail

.card
  .card-body
    %form.form-horizontal#mail{ :data => { :id => id }, :action => mail_activity_participants_path( :activity_id => id ), :method => :post }
      .form-group.row
        %label.col-lg-2.d-none.d-md-block{ :style => 'height: 34px; line-height: 34px; padding-right: 0px;'}= I18n.t('layouts.partials.mail.addressees')
        .col-lg-10.col-sm-12
          .row#recipients
            .col-lg-8
              %input#bbc.form-control{:name => 'recipients', :type => 'text', :value => recipients.map{ |recipient| "#{recipient.member.name} <#{recipient.email}>"}.join(', '), :readonly => true }
            .col-lg-4
              .ui-select
                %select.form-control{ :name => 'recipients', :style => 'width: 100%;'}
                  %option{ :value => 'attendees' }= I18n.t('layouts.partials.mail.attendees')
                  %option{ :value => 'all' }= I18n.t('layouts.partials.mail.all_participants')
                  %option{ :value => 'reservists' }= I18n.t('layouts.partials.mail.reservists')
                  %option{ :value => 'debtors', :selected => 'selected' }= I18n.t('layouts.partials.mail.non_payers')
      .form-group.row
        %label.col-lg-2.d-none.d-md-block{ :style => 'height: 34px; line-height: 34px;'}= I18n.t('layouts.partials.mail.subject')
        .col-lg-10.col-sm-12
          %input#onderwerp.form-control{ :name => 'subject', :type => 'text', :value => "#{I18n.t('association_name')} | #{subject}" }

      .form-group.row
        .col-lg-12
          .editor-container
            %input#html.form-control{ type: "hidden", name: "html" }
            .quill-editor
              - if mail.present?
                = render :template => "mailings/participants/inform", :locals => { subject: subject }

      .form-group.row.mail-actions
        .col-lg-12
          - if recipients.length() > 0
            %button.btn.btn-primary#btn-send{ type: 'submit' }= I18n.t('layouts.partials.mail.send')
          - else
            %button.btn.btn-primary#btn-send{ type: 'submit', :disabled => 'disabled' }= I18n.t('layouts.partials.mail.send')
          .btn.btn-default.disabled{ :disabled => 'disabled' }= I18n.t('layouts.partials.mail.draft')

app/views/layouts/partials/_navigation.html.haml
%aside#sidebar-container{role: 'navigation'}
  #sidebar-wrapper
    .list-group.list-group-flush{'data-collapse-nav' => '', 'data-slim-scroll' => '', 'data-highlight-active' => '' }
      = link_to :root, :class => 'list-group-item list-group-item-action' do
        %span= I18n.t("navigation.home")
        %i.fa.fa-desktop{:class => ('active' if current_page?(:root))}

      = link_to :members, :class => 'list-group-item list-group-item-action' do
        %span= I18n.t("admin.navigation.member")
        %i.fa.fa-user{:class => ('active' if controller_name == 'members')}

      = link_to :groups, :class => 'list-group-item list-group-item-action' do
        %span= I18n.t("admin.navigation.group")
        %i.fa.fa-users{:class => ('active' if controller_name == 'groups')}

      = link_to :activities, :class => 'list-group-item list-group-item-action'do
        %span= I18n.t("navigation.activity")
        %i.fa.fa-ticket-alt{:class => ('active' if controller_name == 'activities')}

      = link_to :posts, :class => 'list-group-item list-group-item-action' do
        %span= I18n.t("admin.navigation.messages")
        %i.fa.fa-file-alt{:class => ('active' if controller_name == 'posts')}

      = link_to :payments, :class => 'list-group-item list-group-item-action' do
        %span= I18n.t("admin.navigation.payments")
        %i.far.fa-money-bill-alt{:class => ('active' if current_page?(:payments))}

      = link_to '', :class => 'list-group-item list-group-item-action',
                    'data-toggle' => 'collapse', 'href' => '#sub-apps' do
        %span= I18n.t("admin.navigation.apps")
        %i.fa.fa-terminal{:class => ('active' if yield(:page) == 'apps')}

      .collapse.list-group#sub-apps{:class => ('show' if yield(:page) == 'apps')}
        = link_to :paymenthandlers, :class => 'list-group-item list-group-item-action' do
          %span= I18n.t("admin.navigation.transactions")
          %i.fa.fa-caret-right{:class => ('active' if current_page?(:paymenthandlers))}

      = link_to '', :class => 'list-group-item list-group-item-action',
                    'data-toggle' => 'collapse', 'href' => '#sub-settings' do
        %span= I18n.t("admin.navigation.settings")
        %i.fas.fa-cog{:class => ('active' if yield(:page) == 'settings')}

      .collapse.list-group#sub-settings{:class => ('show' if yield(:page) == 'settings') }
        = link_to :settings do
          %span= I18n.t("admin.navigation.general")
          %i.fas.fa-caret-right{:class => ('active' if current_page?(settings_path))}

        = link_to :logs_settings, :class => 'list-group-item list-group-item-action' do
          %span= I18n.t("admin.navigation.impressions")
          %i.fas.fa-caret-right{:class => ('active' if current_page?(logs_settings_path))}

      .d-md-none
        = link_to destroy_user_session_path, 'data-method' => :delete do
          %span= I18n.t("devise.sessions.new.sign_out")
          %i.fa.fa-sign-out-alt
            %span.icon-bg.bg-danger

app/views/layouts/partials/_pagination.html.haml
-# The link variable is set to a proc that returns the link tag.
- link = pagy_anchor(pagy, anchor_string: 'class="page-link"')

%nav{"aria-label" => "pager", :role => "navigation"}
  %ul.pagination
    - if pagy.prev
      %li.page-item!= link.(pagy.prev, '&larr;', classes: nil, aria_label: "previous")
    - else
      %li.page-item.disabled
    - pagy.series.each do |item|
      - if item.is_a?(Integer)
        %li.page-item!= link.(item)
      - elsif item.is_a?(String)
        %li.page-item.active!= link.(item)
      - elsif item == :gap
        %li.page-item.disabled.gap
          %a.page-link{:href => "#"}!= pagy_t('pagy.nav.gap')

    - if pagy.next
      %li.page-item!= link.(pagy.next, '&rarr;', classes: nil, aria_label: "next")
    - else
      %li.page-item.disabled

app/views/layouts/partials/_poster_modal.haml
#poster-modal.modal{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %h4.panel-title.activity-title

      .modal-body
        %img.full-width
        %br
        %br
        - if view == 'index'
          %button.btn.btn-info.more-info{"data-dismiss" => "modal"}
            = I18n.t("layouts.partials.poster_modal.more_info")
      .modal-footer
        .col
          %button.btn.btn-default.btn-secondary.prev-activity <
        .col
          %button.btn.btn-default.btn-secondary.full-width{"data-dismiss" => "modal"}= I18n.t("layouts.partials.poster_modal.close")
        .col
          %button.btn.btn-default.btn-secondary.next-activity >

app/views/layouts/partials/_search.html.haml
.page.search
  %section.panel.panel-default
    .panel-body
      = form_tag members_path, :method => 'get' do
        .input-group#search-bar
          = search_field_tag :search, params[:search],  placeholder: I18n.t('layouts.partials.search.placeholder'), class: 'form-control', :autocomplete => 'off'

          %ul.dropdown-menu{ :name => 'studies' }
            - Study.select( :code ).all.map{ |study| [study.code.downcase, I18n.t(study.code.downcase, scope: 'activerecord.attributes.study.names')] }.each do |study|
              %li
                %a{ :data => { :code => study[0], :name => study[1].downcase.gsub( ' ', '-' )} }= study[1]

          %ul.dropdown-menu{ :name => 'tags' }
            - Tag.names.map{ |tag| I18n.t(tag[0], scope: 'activerecord.attributes.tag.names')}.each do |tag|
              %li
                %a{ :data => { :name => tag.downcase.gsub( ' ', '-' )} }= tag

          %ul.dropdown-menu{ :name => 'states' }
            %li
              %a{ :data => { :name => I18n.t("layouts.partials.search.active") }}= I18n.t("layouts.partials.search.active")
            %li
              %a{ :data => { :name => I18n.t("layouts.partials.search.studying") }}= I18n.t("layouts.partials.search.studying")
            %li
              %a{ :data => { :name => I18n.t("layouts.partials.search.alumni") }}= I18n.t("layouts.partials.search.alumni")
            %li
              %a{ :data => { :name => I18n.t("layouts.partials.search.anybody") }}= I18n.t("layouts.partials.search.anybody")

          .input-group-append
            %button.btn.btn-primary{ type: 'submit' }
              %i.fa.fa-search

- if flash['notice'].present?
  .col-md-12
    .alert.alert-info
      %span= I18n.t('activerecord.errors.info')
      %ul
      - Array(flash['notice']).each do |msg|
        %li= msg

app/views/layouts/partials/_search_payments.html.haml
.page.page-item
  %section.panel.panel-default
    .card.card-body
      = form_with url: transactions_path, method: 'get', local: true do |form|
        .input-group
          = form.text_field :search,  placeholder: I18n.t('layouts.partials.search_payments.placeholder'),  class: 'form-control', :autocomplete => 'off',value: params[:search] || ""
          .input-group-append
            .form-element
            .btn.btn-info.dropdown-toggle{'data-toggle' => "dropdown", 'aria-haspopup' => 'true', 'aria-expanded'=>'false', 'tabindex'=>'0'}= I18n.t('admin.transactions.payment_type.title')
            .dropdown-menu.allow-focus
              - Payment.payment_types.keys.each_with_index.map { |transaction, index | [I18n.t(transaction, scope:'admin.transactions.payment_type'), index.to_s] }.each do |val,index|
                %label.dropdown-item{:onclick=>"event.stopPropagation()"}
                  = form.check_box 'payment_type', {:multiple => true,checked: params.has_key?('payment_type') ? params['payment_type'].include?(index):false, :class =>'form-check-input'}, index, nil
                  .form-check-label= val
          .input-group-append
            .btn.btn-info.dropdown-toggle{'data-toggle' => "dropdown", 'aria-haspopup' => 'true', 'aria-expanded'=>'false', 'tabindex'=>'0'}= I18n.t('admin.transactions.transaction_type.title')
            .dropdown-menu.allow-focus
              - Payment.transaction_types.keys.each_with_index.map { |val, index | [I18n.t(val, scope:'admin.transactions.transaction_type'), index.to_s] }.each do |val,index|
                %label.dropdown-item{:onclick=>"event.stopPropagation()"}
                  = form.check_box 'transaction_type', {:multiple => true,checked: params.has_key?('transaction_type') ? params['transaction_type'].include?(index):false, :class =>'form-check-input'}, index, nil
                  .form-check-label= val
          .input-group-append
            .btn.btn-info.dropdown-toggle{'data-toggle' => "dropdown", 'aria-haspopup' => 'true', 'aria-expanded'=>'false', 'tabindex'=>'0'}= I18n.t('admin.transactions.state.title')
            .dropdown-menu.allow-focus
              - Payment.statuses.keys.each_with_index.map { |val, index | [I18n.t(val, scope:'admin.transactions.state'), index.to_s] }.each do |val,index|
                %label.dropdown-item{:onclick=>"event.stopPropagation()"}
                  = form.check_box :status, {:id => val, checked: params.has_key?(:status) ? params[:status].include?(index):false,:multiple => true, :class =>'form-check-input'}, index, nil
                  .form-check-label= val
          .input-group-append
            = button_tag :class => "btn btn-primary" do
              %i.fa.fa-search