config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper_openid_connect

  constraints subdomain: ['wordlid', 'wordlid.dev', 'signup', 'signup.dev', 'join', 'join.dev'] do
    scope module: 'public' do
      get  '/', to: 'home#index', as: 'public'
      post '/', to: 'home#create'
    end
  end

  constraints subdomain: ['koala', 'koala.dev', 'leden', 'leden.dev', 'members', 'members.dev'] do
    authenticate :user, ->(u) { !u.admin? } do
      scope module: 'members' do
        root to: 'home#index', as: :users_root

        get '/activities/69420', to: redirect('/CommITCrowd.jpg')

        get   'edit',                           to: 'home#edit', as: :users_edit
        post  'edit',                           to: 'home#update'
        delete 'authorized_applications/:id',   to: 'home#revoke', as: :authorized_applications

        get 'download', to: 'home#download'

        get 'member/payments', to: 'payments#index', as: :member_payments

        post 'mongoose', to: 'payments#add_funds'
        post 'pay_activities', to: 'payments#pay_activities'

        resources :activities, only: [:index, :show] do
          resource :participants, only: [:create, :update, :destroy]
        end
      end
    end

    root 'admin/home#index'

    # No double controllers
    get     'admin/home',   to: redirect('/')
    get     'members/home', to: redirect('/')

    # Devise routes
    devise_for :users, path: '', skip: [:registrations], controllers: {
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

    # update account with password after receiving invite
    get     'activate',     to: 'users/registrations#edit', as: :new_member_confirmation
    post    'activate',     to: 'users/registrations#update', as: :new_member_confirm

    # update password from member options
    get     'passwordchange',     to: 'users/password_change#edit', as: :password_change
    patch   'passwordchange',     to: 'users/password_change#update'

    scope module: 'public' do
      get   'status(/:token)', to: 'status#edit'
      post  'status',          to: 'status#update'
      post  'status/destroy',  to: 'status#destroy'
    end

    scope module: 'admin' do
      resources :members do
        get   'payment_whatsapp'
        patch 'force_email_change'
        post  'email/:type', to: 'members#send_email', as: :mail
        patch 'set_card_disabled/:uuid', to: 'members#set_card_disabled', as: 'set_card_disabled'

        collection do
          get 'search'
        end
      end

      resources :activities do
        resources :participants, only: [:create, :update, :destroy] do
          collection do
            post 'mail'
          end
        end
        get 'committee_members'
      end

      scope 'payments' do
        get '/', to: 'payments#index', as: "payments"
        get 'whatsapp/:member_id', to: 'payments#whatsapp_redirect', as: 'payment_whatsapp_redirect'
        get 'transactions', to: 'payments#update_transactions'
        get 'transactions_export', to: 'payments#export_payments'
      end

      resources :posts, only: [:index, :show, :create, :update, :destroy]

      resources :groups, only: [:index, :create, :show, :update, :destroy] do
        resources :group_members, only: [:create, :update, :destroy], path: 'members'
      end

      resources :settings, only: [:index, :create] do
        collection do
          get 'logs'
          patch 'profile', to: 'settings#profile'
        end
      end

      scope 'apps' do
        get 'payments',           to: 'apps#transactions', as: 'paymenthandlers'
        get 'checkout',           to: 'apps#checkout'

        # json checkout urls
        patch  'cards',           to: 'checkout_products#activate_card'
        patch  'transactions',    to: 'checkout_products#change_funds'

        resources :checkout_products, only: [:index, :show, :create, :update], path: 'products' do
          patch :flip, action: :flip_active
          match :flip, action: :flip_active, via: [:patch]
        end
      end

      # sidekiq web interface
      authenticate :user, ->(u) { u.admin? } do
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end
    end

    scope 'api' do
      use_doorkeeper do
        # skip_controllers :token_info, :applications, :authorized_applications
      end

      scope module: 'api' do
        resources :members, only: [:index, :show, :create] do
          resources :participants, only: :index
        end

        resources :groups, only: [:index, :show]

        resources :activities, only: [:index, :show] do
          resources :participants
          get 'poster'
          get 'thumbnail'
        end

        scope 'hook' do
          get 'payment/:token', to: 'webhook#payment_redirect', as: 'payment_redirect'

          post 'mollie',        to: 'webhook#mollie_hook',        as: 'mollie_hook'

          get 'mailchimp/:token', to: 'webhook#mailchimp_confirm_callback', as: 'mailchimp_confirm'
          post 'mailchimp/:token', to: 'webhook#mailchimp', as: 'mailchimp'
        end

        # NOTE: legacy implementation for checkout without oauth
        scope 'checkout' do
          get  'card',          to: 'checkout#info'
          get  'recent',        to: 'checkout#recent'
          post 'card',          to: 'checkout#create'
          get  'confirmation',  to: 'checkout#confirm'

          get  'products',      to: 'checkout#products'
          post 'transaction',   to: 'checkout#purchase'
        end

        scope 'internal' do
          get 'member_by_id',        to: 'internal#member_by_id'
          get 'member_by_studentid', to: 'internal#member_by_studentid'
        end
      end
    end
  end

  get '/', to: redirect('/404')
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  protect_from_forgery except: [:information_for_card, :subtract_funds, :add_card_to_member]
  
  skip_before_action :authenticate_user!, only: [:information_for_card, :subtract_funds, :add_card_to_member]
  skip_before_action :authenticate_admin!, only: [:information_for_card, :subtract_funds, :add_card_to_member]
    
  before_action :authenticate_checkout, only: [:information_for_card, :subtract_funds, :add_card_to_member]
  
  respond_to :json
  respond_to :html, only: :index
  
  def index    
    @limit = params[:limit] ? params[:limit].to_i : 50
    @offset = params[:offset] ? params[:offset].to_i : 0
  
    @page = @offset / @limit
    @pagination = 5
 
    @transactions = CheckoutTransaction.includes(:checkout_card).order(created_at: :desc).limit(@limit).offset(@offset)
    @cards = CheckoutCard.joins(:member).select(:id, :uuid, :member_id).where(:active => false)
    
    @pages = CheckoutTransaction.count / @limit
  end

  def information_for_card
    respond_with CheckoutCard.joins(:member, :checkout_balance).select(:id, :uuid, :first_name, :balance).find_by_uuid!(params[:uuid])
  end

  def change_funds  
    if !params[:amount].is_number?
      render :status => :bad_request, :json => 'amount should be a numeric value'
      return
    end
    
    if params[:uuid]
      card = CheckoutCard.joins(:checkout_balance).find_by_uuid(params[:uuid])
      transaction = CheckoutTransaction.new( :price => params[:amount], :checkout_card => card )
      
    elsif params[:member_id]        
      transaction = CheckoutTransaction.new( :price => params[:amount], :checkout_balance => CheckoutBalance.find_by_member_id!(params[:member_id]) )

    else
      render :status => :bad_request, :json => 'no identifier given'
      return
    end
    
    begin
      transaction.save
    rescue ActiveRecord::RecordNotSaved
      render :status => :request_entity_too_large, :json => 'insufficient funds'
      return
    end
    
    render :status => :created, :json => transaction
  end
  
  def subtract_funds
    if !params[:amount].is_number? || params[:amount].to_f >= 0
      render :status => :bad_request, :json => 'amount should be a negative numeric value'
      return
    end
    
    card = CheckoutCard.find_by_uuid!(params[:uuid])
    
    if( !card.active )
      render :status => :unauthorized, :json => 'card not yet activated'
      return
    end
    
    #in the constructor of transaction subtract from balance, check if it is a subtraction
    transaction = CheckoutTransaction.new( :price => params[:amount], :checkout_card => card )

    logger.debug transaction.inspect

    begin
      transaction.save
    rescue ActiveRecord::RecordNotSaved
      render :status => :request_entity_too_large, :json => 'insufficient funds'
      return
    end
  
    render :status => :created, :json => CheckoutTransaction.joins(:checkout_card).select(:id, :uuid, :price, :created_at).find_by_id!(transaction.id)
  end
  
  def add_card_to_member    
    if !CheckoutCard.find_by_uuid(params[:uuid]).nil?
      render :status => :conflict, :json => 'card already registered'
      return
    end
    
    card = CheckoutCard.new( :uuid => params[:uuid], :member => Member.find_by_student_id!(params[:student]), :description => params[:description] )
    
    if card.save(:validate => false)
      render :status => :created, :json => CheckoutCard.joins(:member, :checkout_balance).select(:id, :uuid, :first_name, :balance).find_by_uuid!(params[:uuid]).to_json
      return
    else
      render :status => :conflict, :json => card.errors.full_messages
      return
    end
  end
  
  def activate_card
    card = CheckoutCard.find_by_uuid!(params[:uuid])
    card.update_attribute(:active, true);
    
    if card.save
      render :status => :ok, :json => card.to_json
      return
    else 
      render :status => :bad_request, :json => card.errors.full_messages
      return
    end
  end
  
  private 
  def authenticate_checkout
    if params[:token] != ConstipatedKoala::Application.config.checkout
      render :status => :forbidden, :json => 'not authenticated'
      return
    end
  end
end

app/views/admins/checkout/index.html.haml
- content_for(:page, 'checkout')
- content_for(:subpage, 'transacties')

- content_for(:title, 'Constipated koala | checkout | transacties') 

%section#content
  = render 'layouts/search' 

  .page.page-table{ :data => { 'authenticity_token' => form_authenticity_token}}
    .row
      .col-lg-8
        %section.panel.panel-default.table-dynamic
          .panel-heading
            %i.fa.fa-fw.fa-fw.fa-shopping-cart
            Transacties
          .table-responsive#transactions
            %table.table.table-bordered.table-striped.table-linked
              %thead
                %tr
                  %th
                    .th
                      Datum
                  %th
                    .th
                      Prijs
                  %th
                    .th
                      Lid
                  %th.hidden-xs
                    .th
                      Kaart
                        
              - @transactions.each do |transaction|
                %tr
                  %td #{I18n.l transaction.created_at}
                  %td
                    = number_to_currency(transaction.price, :unit => '€')
                    - if transaction.price > 0
                      %span.fa.fa-sort-asc.pull-right{ :style => 'padding-up: 3px;'}
                    - else
                      %span.fa.fa-sort-desc.pull-right
                  
                  %td
                    - unless transaction.checkout_balance.member.nil?
                      = link_to "#{transaction.checkout_balance.member.name}", transaction.checkout_balance.member
                    - else
                      \-
                  
                  %td.hidden-xs
                    - unless transaction.checkout_card.nil?
                      = transaction.checkout_card.uuid
                    - else
                      \-
               
          %footer.table-footer
            .row
              .col-md-6.page-num-info.hidden-xs{ :data => { :limit => @limit, :pagination => @pagination } }
                %span
                  Toon
                  = select_tag 'limit', options_for_select([20,50,100], @limit)
                  transacties per pagina
                  
              .col-md-6.text-right.pagination-container
                %ul.pagination-sm.pagination
                  %li{ :class => ( 'disabled' if @offset == 0)}
                    %a{ :data => { :offset => @offset - @limit }} vorige
                    
                  %li.scroll{ :class => ( 'disabled' if @page / @pagination == 0)}
                    %a{ :data => { :offset => (@page / @pagination * @pagination -1) * @limit }} <<
                    
                  - (0 .. @pages).each do |i|
                    - if i == @page
                      %li.active
                        - if i.between?(@pagination * (@page / @pagination), @pagination * (@page / @pagination) + @pagination -1 )
                          %a{ :data => { :offset => @limit * i }}= i+1
                        -else 
                          %a.hidden{ :data => { :offset => @limit * i }}= i+1
                    - else
                      %li
                        - if i.between?(@pagination * (@page / @pagination), @pagination * (@page / @pagination) + @pagination -1 )
                          %a{ :data => { :offset => @limit * i }}= i+1    
                        - else
                          %a.hidden{ :data => { :offset => @limit * i }}= i+1    
    
                  %li.scroll{ :class => ( 'disabled' if @pages / @pagination * @pagination <= @page )}
                    %a{ :data => { :offset => (@page / @pagination +1) * @pagination * @limit }} >>
                        
                  %li{ :class => ( 'disabled' if @offset == @limit * @pages )}
                    %a{ :data => { :offset => @offset + @limit }} volgende
                    
      .col-lg-4#credit
        .panel.panel-default
          .panel-heading
            %i.fa.fa-fw.fa-money
            Opwaarderen
          .panel-body{ :style => 'position: relative;' }
            %form.form-inline
              .form-group.col-md-12#card
                %input.form-control#card_holder{ :placeholder => 'zoek lid op voornaam, achternaam, of studentnummer', :tabindex => '-1' }
                %ul.dropdown-menu.col-md-12
              
              .form-group.col-md-3.amount{ :style => 'display: none;' }
                %input.form-control#amount{ :placeholder => 'hoeveel', :autocomplete => 'off' }

              .form-group.col-md-3{ :style => 'display: none;' }         
                %button.form-control.btn.btn-line-primary opslaan
            
      .col-lg-4#cards
        .panel.panel-default
          .panel-heading
            %i.fa.fa-fw.fa-credit-card
            Niet geactiveerde kaarten
          %ul.list-group
            - @cards.each do |card|
              %li.list-group-item{ :data => { 'uuid' => card.uuid }}
                %p= link_to "#{card.member.name}", card.member
                %p.uuid= card.uuid
                .btn-group
                  %button.btn.btn-primary activeer
                  %button.btn.btn-line-primary verwijder
            - if @cards.length == 0
              %li.list-group-item
                %p.text-center 
                  %em geen kaarten
          

app/views/admins/checkout/products.html.haml
- content_for(:page, 'checkout')
- content_for(:subpage, 'products')

- content_for(:title, 'Constipated koala | checkout | producten') 

%section#content
  = render 'layouts/search'

  .page.page-form{ :data => { 'authenticity_token' => form_authenticity_token}}
    .row
      .col-md-6.hidden-xs
        .panel.panel-default
          .panel-heading
            %i.fa.fa-fw.fa-ticket
            Producten
            
          %table.table.table-striped.table-linked#products
            %tbody
              - @products.each do |product|
                %tr{ :data => { 'id' => product.id }}
                  %td= link_to product.name, product.image.url(:original)
                  %td= I18n.t( product.category, scope: 'activerecord.attributes.checkout_product.categories' ).downcase
                  %td= number_to_currency( product.price, :unit => '€' )
                  %td.buttons
                    .btn-group
                      %button.btn.btn-default.destroy
                        %i.fa.fa-fw.fa-trash-o
                    

      = form_for :checkout_product, url: checkout_products_path, method: :post, :class => 'form-validation' do |f|   
        - if @product.errors.any?
          .col-md-6
            .alert.alert-danger
              %button.close{ type: "button" } ×
              %span Oeps, niet alles is goed ingevuld;
              %ul
              - @product.errors.full_messages.each do |msg|
                %li= msg
        
        .col-md-6
          .panel.panel-default
            .panel-heading
              %i.fa.fa-fw.fa-ticket
              Nieuw product
            .panel-body
            
              .form-group
                .row
                  .col-md-8              
                    = label(:checkout_product, :name)
                    = f.text_field :name, :value => @product.name, :class => 'form-control'
                  .col-md-4
                    = label(:checkout_product, :price)
                    = f.text_field :price, :value => number_to_currency(@product.price, :unit => ''), :class => 'form-control'
                
              .form-group
                .row
                  .col-md-4
                    = label(:checkout_product, :category)
                    .ui-select
                      = f.select :category, options_for_select( CheckoutProduct.categories.map{ |name, id| [I18n.t(name, scope: 'activerecord.attributes.checkout_product.categories'), name] }, @product.category )
                  .col-md-8
                    = label(:checkout_product, :image)
                    .input-group
                      %input#output.form-control{ :readonly => ''}
  
                      .input-group-btn
                        %button.btn.btn-primary.file-input-wrapper
                          %span uploaden
                          = f.file_field :image, { 'data-ui-file-upload' => '' }    

              %button.btn.btn-success.wait{type: 'submit'} Opslaan
              = link_to 'Annuleren', checkout_products_path, { :class => 'button btn btn-default' }